---

- name: Install PHP7 yum source
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present

- name: Makecache for new yum source
  command: yum makecache

- name: Install php and deps
  yum: name={{ item }} state=present
  with_items:
    - php72w-common
    - php72w-mysql
    - php72w-mbstring
    - php72w-xml
    - php72w-gd
    - mod_php72w
  notify: restart httpd