---
- name: Install EPEL yum source
  yum: name=epel-release state=present

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  service: name=firewalld state=started enabled=yes

- name: Set SELinux to permissive mode
  shell: setenforce 0
  ignore_errors: True

- name: Disable SELinux
  copy: src=config dest=/etc/selinux/config

