---
- name: Install Apache, PHP, MariaDB, Zabbix-Server, Zabbix-Web-Mysql and Zabbix-Agent
  hosts: zabbix-servers
  remote_user: root

  roles:
    - common
    - httpd
    - mariadb
    - zabbix_server

